pipeline {    
    options { skipDefaultCheckout() }
    agent {label 'linux'} 

    parameters {
        string(name: 'TAGImage', defaultValue: 'tagimage', description: 'tag image')
       
    }

stages{
    stage('Clean Workspace') {
        steps{
        cleanWs()
        }
    }
    stage('Clone repository'){
        steps{
        checkout scm
        }
    }
    stage ('modify manifest'){
        steps{
        script{
            
                withCredentials([usernamePassword(credentialsId: '9813091d-d878-41ff-8b14-578bd8fa9f7b', passwordVariable: 'GIT_PASSWORD' , usernameVariable: 'GIT_USERNAME')]){
                
                    sh "cat manifest/manifest.yaml"
                    
                    sh "sed -i 's+192.168.0.128:5567/esbonline/esbonline.*+192.168.0.128:5567/esbonline/esbonline:$TAGImage+g' manifest/manifest.yaml"
                }
        }
        }
    }
    stage ('Update GIT'){
        steps{
            script{
                sh '''
                    git add .
                    git config user.email "bilel.marzouk@esprit.tn"
                    git config user.name "bilel.marzouk"
                    git config  --global user.email "bilel.marzouk@esprit.tn"
                    git config  --global user.name "bilel.marzouk"
                    git commit -m "Done by jenkins job changemanifest:${TAGImage}"
                    git push https://$GIT_USERNAME:$GIT_PASSWORD@github.com/$GIT_USERNAME/ESBOnline-PFE HEAD:master
                    '''

            }
        }
    }          
    }
}
 