apiVersion: v1
kind: Service
metadata:
  name: esbonline
  labels:
    app: esbonline
spec:
  ports:
    # the port that this service should serve on
    - port: 80
      targetPort: 80
  selector:
    app: esbonline
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: esbonline
  name: esbonline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: esbonline
  template:
    metadata:
      labels:
        app: esbonline
      name: esbonline
    spec:
     containers:
      - name: esbonline
        image: docker.io/bilelm1/esbonline:2
        ports:
        - containerPort: 80
     nodeSelector:
      kubernetes.io/os: windows