apiVersion: v1
kind: PersistentVolume
metadata:
  name: esbonline-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.0.128
    path: /export/esbonline-data
  claimRef:
    namespace: esbonline2
    name: esbonline-pvc

  commentaire
