FROM mcr.microsoft.com/dotnet/framework/sdk:4.8 AS build



RUN Invoke-WebRequest 'https://github.com/git-for-windows/git/releases/download/v2.12.2.windows.2/MinGit-2.12.2.2-64-bit.zip' -OutFile MinGit.zip

RUN Expand-Archive c:\MinGit.zip -DestinationPath c:\MinGit; \
$env:PATH = $env:PATH + ';C:\MinGit\cmd\;C:\MinGit\cmd'; \
Set-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\Environment\' -Name Path -Value $env:PATH





RUN Invoke-WebRequest -Uri http://192.168.0.128:9080/jnlpJars/agent.jar -OutFile agent.jar



RUN Invoke-WebRequest -Uri https://download.java.net/java/GA/jdk11/9/GPL/openjdk-11.0.2_windows-x64_bin.zip -OutFile C:\openjdk-11.0.2_windows-x64_bin.zip ; \
    Expand-Archive -Path C:\openjdk-11.0.2_windows-x64_bin.zip -DestinationPath C:\java ; \
    Remove-Item C:\openjdk-11.0.2_windows-x64_bin.zip -Force ; \
    setx /M PATH $('C:\java\jdk-11.0.2\bin;' + $env:PATH)











RUN java -jar agent.jar -jnlpUrl http://192.168.0.128:9080/manage/computer/docker%2Dwindows/jenkins-agent.jnlp -secret 932151cdb95f10fcbcf5fe9738f2364ca30c26f3192fc634e0c4f0665935c2cb -workDir "c:/jenkins"



CMD ["powershell.exe"]