apiVersion: v1
kind: Service
metadata:
  name: esbonline
  namespace: esbonline2
  labels:
    app: esbonline
spec:
  ports:
    # the port that this service should serve on
    - port: 80
      targetPort: 80
  selector:
    app: esbonline
  type: NodePort
  #loadBalancerIP: 192.168.0.131
  #externalTrafficPolicy: Local
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: esbonline
  namespace: esbonline2
  labels:
    app: esbonline
spec:
  replicas: 2
  selector:
    matchLabels:
      app: esbonline
  template:
    metadata:
      labels:
        app: esbonline
      name: esbonline
    spec:
      containers:
        - name: esbonline
          image: 192.168.0.128:5567/esbonline/esbonline:619ad1
          #docker.io/bilelm1/esbonline:01
          ports:
          - containerPort: 80
      nodeSelector:
        kubernetes.io/os: windows
          
      #volumes:
       # - name: esbonline-data
        #  persistentVolumeClaim:
         #   claimName: esbonline-pvc
 






      
