apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: esbonline-pvc
  namespace: esbonline2
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: samba-storage
  resources:
    requests:
      storage: 5Gi
  volumeName: esbonline-pv