apiVersion: v1
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 3m
      smtp_smarthost: smtp.gmail.com:587
      smtp_from: alertmanager.pfe@esprit.tn
      smtp_auth_username: alertmanager.pfe@esprit.tn
      smtp_auth_password: espritpfe2023+
    receivers:
      - name: default-receiver
        email_configs:
        - to: mohamedbilel.marzouk@esprit.tn
    route:
      group_wait: 10s
      group_interval: 20m
      receiver: default-receiver
      repeat_interval: 1h  
    templates:
    - /etc/alertmanager/*.tmpl
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: prometheus
    meta.helm.sh/release-namespace: prometheus
  
  labels:
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/version: v0.25.0
    helm.sh/chart: alertmanager-0.30.1
  name: prometheus-alertmanager
  namespace: prometheus

